<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" tests="15" skipped="0" failures="0" errors="0" timestamp="2025-09-30T21:39:49" hostname="MacBook-Air-de-Kaique.local" time="1.96">
  <properties/>
  <testcase name="given a request to authorize when user not found should thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.794"/>
  <testcase name="given a request to authorize based on code when code challenge not matches should thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.136"/>
  <testcase name="given a request to authorize when password does not match should thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.14"/>
  <testcase name="given a request to authorize should create a authorization code successfully()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.146"/>
  <testcase name="given a request to introspect when access token has a invalid signature should thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.146"/>
  <testcase name="given a request to authorize based on refresh token when request is invalid thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.013"/>
  <testcase name="given a request to authorize based on code when request is invalid thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.011"/>
  <testcase name="given a request to introspect when access token has a invalid format should thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.011"/>
  <testcase name="given a request to authorize based on refresh token when not exist a session should thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.018"/>
  <testcase name="given a request to introspect when session is expired and revoked should return the introspection data with active false()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.132"/>
  <testcase name="iven a request to introspect when session is not expired and not revoked should return the introspection data with active true()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.119"/>
  <testcase name="given a request to introspect when access token is expired should thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.085"/>
  <testcase name="given a request to authorize based on refresh token should return a pair of tokens successfully()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.098"/>
  <testcase name="given a request to authorize based on code should return a pair of tokens successfully()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.093"/>
  <testcase name="given a request to authorize based on code should when code not exists thrown an exception()" classname="com.kaiqkt.authentication.integration.web.OAuthIntegrationTest" time="0.011"/>
  <system-out><![CDATA[Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
18:39:41.521 [Test worker] INFO org.springframework.test.context.support.AnnotationConfigContextLoaderUtils -- Could not detect default configuration classes for test class [com.kaiqkt.authentication.integration.web.OAuthIntegrationTest]: OAuthIntegrationTest does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
18:39:41.582 [Test worker] INFO org.springframework.boot.test.context.SpringBootTestContextBootstrapper -- Found @SpringBootConfiguration com.kaiqkt.authentication.AuthenticationApplication for test class com.kaiqkt.authentication.integration.web.OAuthIntegrationTest

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.5.5)

2025-09-30T18:39:41.817-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] c.k.a.i.web.OAuthIntegrationTest         : Starting OAuthIntegrationTest using Java 21.0.8 with PID 16238 (started by kaiqkt in /Volumes/hd-externo/Projects/kt-authentication-api)
2025-09-30T18:39:41.819-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] c.k.a.i.web.OAuthIntegrationTest         : No active profile set, falling back to 1 default profile: "default"
2025-09-30T18:39:42.290-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2025-09-30T18:39:42.320-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 26 ms. Found 3 JPA repository interfaces.
2025-09-30T18:39:42.561-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 0 (http)
2025-09-30T18:39:42.569-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2025-09-30T18:39:42.569-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.44]
2025-09-30T18:39:42.597-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2025-09-30T18:39:42.597-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 655 ms
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2025-09-30T18:39:42.718-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2025-09-30T18:39:42.746-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.testcontainers.images.PullPolicy     : Image pull policy will be performed by: DefaultPullPolicy()
2025-09-30T18:39:42.747-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.t.utility.ImageNameSubstitutor         : Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2025-09-30T18:39:42.752-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.testcontainers.DockerClientFactory   : Testcontainers version: 1.21.3
2025-09-30T18:39:42.875-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.t.d.DockerClientProviderStrategy       : Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2025-09-30T18:39:43.015-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.t.d.DockerClientProviderStrategy       : Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2025-09-30T18:39:43.016-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.testcontainers.DockerClientFactory   : Docker host IP address is localhost
2025-09-30T18:39:43.030-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.testcontainers.DockerClientFactory   : Connected to docker: 
  Server Version: 28.3.3
  API Version: 1.51
  Operating System: Ubuntu 24.04.2 LTS
  Total Memory: 1959 MB
2025-09-30T18:39:43.084-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] tc.testcontainers/ryuk:0.12.0            : Creating container for image: testcontainers/ryuk:0.12.0
2025-09-30T18:39:43.165-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] tc.testcontainers/ryuk:0.12.0            : Container testcontainers/ryuk:0.12.0 is starting: 94a784d226c47f0576b3cdea658bba9f1305cfeebf5d72ddf2fe7a980311b7be
2025-09-30T18:39:43.331-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] tc.testcontainers/ryuk:0.12.0            : Container testcontainers/ryuk:0.12.0 started in PT0.247387S
2025-09-30T18:39:43.333-03:00  WARN 16238 --- [kt-authentication-api] [containers-ryuk] o.t.utility.RyukResourceReaper           : Can not connect to Ryuk at localhost:32768

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$0(RyukResourceReaper.java:92) ~[testcontainers-1.21.3.jar:1.21.3]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88) ~[testcontainers-1.21.3.jar:1.21.3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-30T18:39:43.590-03:00  WARN 16238 --- [kt-authentication-api] [containers-ryuk] o.t.utility.RyukResourceReaper           : Can not connect to Ryuk at localhost:32768

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$0(RyukResourceReaper.java:92) ~[testcontainers-1.21.3.jar:1.21.3]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88) ~[testcontainers-1.21.3.jar:1.21.3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-30T18:39:43.846-03:00  WARN 16238 --- [kt-authentication-api] [containers-ryuk] o.t.utility.RyukResourceReaper           : Can not connect to Ryuk at localhost:32768

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$0(RyukResourceReaper.java:92) ~[testcontainers-1.21.3.jar:1.21.3]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88) ~[testcontainers-1.21.3.jar:1.21.3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-30T18:39:44.099-03:00  WARN 16238 --- [kt-authentication-api] [containers-ryuk] o.t.utility.RyukResourceReaper           : Can not connect to Ryuk at localhost:32768

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$0(RyukResourceReaper.java:92) ~[testcontainers-1.21.3.jar:1.21.3]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88) ~[testcontainers-1.21.3.jar:1.21.3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-30T18:39:44.356-03:00  WARN 16238 --- [kt-authentication-api] [containers-ryuk] o.t.utility.RyukResourceReaper           : Can not connect to Ryuk at localhost:32768

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$0(RyukResourceReaper.java:92) ~[testcontainers-1.21.3.jar:1.21.3]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88) ~[testcontainers-1.21.3.jar:1.21.3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-30T18:39:44.614-03:00  WARN 16238 --- [kt-authentication-api] [containers-ryuk] o.t.utility.RyukResourceReaper           : Can not connect to Ryuk at localhost:32768

java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:751) ~[na:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$0(RyukResourceReaper.java:92) ~[testcontainers-1.21.3.jar:1.21.3]
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$1(RyukResourceReaper.java:88) ~[testcontainers-1.21.3.jar:1.21.3]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

2025-09-30T18:39:44.883-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.t.utility.RyukResourceReaper           : Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
2025-09-30T18:39:44.884-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.testcontainers.DockerClientFactory   : Checking the system...
2025-09-30T18:39:44.885-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.testcontainers.DockerClientFactory   : ✔︎ Docker server version should be at least 1.6.0
2025-09-30T18:39:44.886-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] tc.postgres:15.3                         : Creating container for image: postgres:15.3
2025-09-30T18:39:44.957-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] tc.postgres:15.3                         : Container postgres:15.3 is starting: 862a6af13802b73bea5fb573306a0d6fd92cc0c4fb19e03d4307a26b5ef3a8be
2025-09-30T18:39:45.721-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] tc.postgres:15.3                         : Container postgres:15.3 started in PT0.835016S
2025-09-30T18:39:45.722-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] tc.postgres:15.3                         : Container is started (JDBC URL: jdbc:postgresql://localhost:32769/test?loggerLevel=OFF)
2025-09-30T18:39:47.891-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.testcontainers.jdbc.ConnectionWrapper@15d713d
2025-09-30T18:39:47.892-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2025-09-30T18:39:47.936-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.f.c.i.s.JdbcTableSchemaHistory         : Schema history table "public"."flyway_schema_history" does not exist yet
2025-09-30T18:39:47.938-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.f.core.internal.command.DbValidate     : Successfully validated 1 migration (execution time 00:00.009s)
2025-09-30T18:39:47.950-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table "public"."flyway_schema_history" ...
2025-09-30T18:39:47.999-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.f.core.internal.command.DbMigrate      : Current version of schema "public": << Empty Schema >>
2025-09-30T18:39:48.007-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.f.core.internal.command.DbMigrate      : Migrating schema "public" to version "1 - Create tables"
2025-09-30T18:39:48.030-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.f.core.internal.command.DbMigrate      : Successfully applied 1 migration to schema "public", now at version v1 (execution time 00:00.010s)
2025-09-30T18:39:48.080-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2025-09-30T18:39:48.106-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.6.26.Final
2025-09-30T18:39:48.124-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
2025-09-30T18:39:48.259-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2025-09-30T18:39:48.306-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] org.hibernate.orm.connections.pooling    : HHH10001005: Database info:
	Database JDBC URL [Connecting through datasource 'HikariDataSource (HikariPool-1)']
	Database driver: undefined/unknown
	Database version: 15.3
	Autocommit mode: undefined/unknown
	Isolation level: undefined/unknown
	Minimum pool size: undefined/unknown
	Maximum pool size: undefined/unknown
2025-09-30T18:39:48.722-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000489: No JTA platform available (set 'hibernate.transaction.jta.platform' to enable JTA platform integration)
2025-09-30T18:39:48.723-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2025-09-30T18:39:49.008-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.s.d.j.r.query.QueryEnhancerFactory     : Hibernate is in classpath; If applicable, HQL parser will be used.
2025-09-30T18:39:49.457-03:00  WARN 16238 --- [kt-authentication-api] [    Test worker] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2025-09-30T18:39:49.676-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 54208 (http) with context path '/'
2025-09-30T18:39:49.680-03:00  INFO 16238 --- [kt-authentication-api] [    Test worker] c.k.a.i.web.OAuthIntegrationTest         : Started OAuthIntegrationTest in 8.025 seconds (process running for 8.711)
2025-09-30T18:39:50.407-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2025-09-30T18:39:50.407-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2025-09-30T18:39:50.408-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
2025-09-30T18:39:50.982-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-4] c.k.a.d.services.AuthorizationService    : Authorization code created for user 01K6E92HXZ92RHYRD6PSPRG5S4
2025-09-30T18:39:51.619-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-6] c.k.a.d.services.AuthorizationService    : Session 01K6E92JNG5V1EV5VT83J0BZTM persisted for user 01K6E92JKDPD9T3HQVKAY4DYP1 successfully
2025-09-30T18:39:51.619-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-6] c.k.a.d.services.AuthenticationService   : Authentication for session 01K6E92JNG5V1EV5VT83J0BZTM of user 01K6E92JKDPD9T3HQVKAY4DYP1 successfully
2025-09-30T18:39:51.717-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-5] c.k.a.d.services.AuthorizationService    : Session 01K6E92JS34B445FFXH1MQTRTC persisted for user 01K6E92JPG3V42DV3J4AHB0QNC successfully
2025-09-30T18:39:51.718-03:00  INFO 16238 --- [kt-authentication-api] [o-auto-1-exec-5] c.k.a.d.services.AuthenticationService   : Authenticated 01K6E92JPG3V42DV3J4AHB0QNC successfully
]]></system-out>
  <system-err><![CDATA[Mockito is currently self-attaching to enable the inline-mock-maker. This will no longer work in future releases of the JDK. Please add Mockito as an agent to your build as described in Mockito's documentation: https://javadoc.io/doc/org.mockito/mockito-core/latest/org.mockito/org/mockito/Mockito.html#0.3
WARNING: A Java agent has been loaded dynamically (/Users/kaiqkt/.gradle/caches/modules-2/files-2.1/net.bytebuddy/byte-buddy-agent/1.17.7/fbf3d6d649ed37fc9e9c59480a05be0a26e3c2da/byte-buddy-agent-1.17.7.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
]]></system-err>
</testsuite>
